# Generated by Django 6.0.6 on 2026-06-25 08:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_variants', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('tax_inclusive', models.BooleanField(default=False)),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('free_shipping', models.BooleanField(default=False)),
                ('minimum_order_quantity', models.IntegerField(default=1)),
                ('max_order_quantity', models.IntegerField(blank=True, null=True)),
                ('warranty_type', models.CharField(blank=True, max_length=50, null=True)),
                ('warranty_period', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_time_days', models.IntegerField(blank=True, null=True)),
                ('estimated_delivery', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_till', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='sellers.sellerprofile')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_pricing', to='product_variants.productvariant')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sellers.sellerwarehouse')),
            ],
            options={
                'verbose_name': 'Seller Pricing',
                'verbose_name_plural': 'Seller Pricing',
                'db_table': 'seller_pricing',
                'ordering': ['selling_price'],
                'unique_together': {('seller', 'variant')},
            },
        ),
    ]
