# Generated by Django 6.0.6 on 2026-06-25 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerpricing',
            name='wholesale_price',
        ),
        migrations.CreateModel(
            name='WholesaleTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_quantity', models.IntegerField(help_text='Minimum quantity for this tier (inclusive)')),
                ('max_quantity', models.IntegerField(blank=True, help_text='Maximum quantity (inclusive). NULL = unlimited', null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per unit at this tier', max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount % off MRP', max_digits=5)),
                ('notes', models.CharField(blank=True, help_text='Internal notes for this tier', max_length=200, null=True)),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_tiers', to='pricing.sellerpricing')),
            ],
            options={
                'verbose_name': 'Wholesale Tier',
                'verbose_name_plural': 'Wholesale Tiers',
                'db_table': 'wholesale_tiers',
                'ordering': ['min_quantity'],
                'constraints': [models.UniqueConstraint(fields=('pricing', 'min_quantity'), name='unique_tier_per_pricing')],
            },
        ),
    ]
