# Generated by Django 6.0.6 on 2026-06-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='categories_parent__c20446_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['level', 'is_active'], name='categories_level_5da82b_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_featured', 'is_active'], name='categories_is_feat_9b3b1e_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_category_name_per_parent'),
        ),
    ]
