# Generated by Django 6.0.6 on 2026-06-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_deleted_at_category_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma-separated aliases, misspellings, and related terms for search matching', null=True),
        ),
    ]
