# Generated by Django 6.0.6 on 2026-06-29 06:06

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='gstin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[common.validators.validate_gstin]),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[common.validators.validate_pan]),
        ),
    ]
