# Generated by Django 6.0.6 on 2026-06-25 07:45

import common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gstin', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[common.validators.validate_gstin])),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, validators=[common.validators.validate_pan])),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyer Profile',
                'verbose_name_plural': 'Buyer Profiles',
                'db_table': 'buyer_profiles',
            },
        ),
        migrations.CreateModel(
            name='BuyerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=10)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=15, validators=[common.validators.validate_phone])),
                ('address_line1', models.CharField(max_length=500)),
                ('address_line2', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10, validators=[common.validators.validate_pincode])),
                ('country', models.CharField(default='India', max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='buyers.buyerprofile')),
            ],
            options={
                'verbose_name': 'Buyer Address',
                'verbose_name_plural': 'Buyer Addresses',
                'db_table': 'buyer_addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
