# Generated by Django 6.0.6 on 2026-06-29 10:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0002_brand_country_brand_founded_year_brand_image_and_more'),
        ('categories', '0002_category_deleted_at_category_is_featured_and_more'),
        ('sellers', '0002_alter_sellerprofile_gstin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_type', models.CharField(choices=[('category', 'Category'), ('category_city', 'Category + City'), ('category_brand', 'Category + Brand'), ('category_brand_city', 'Category + Brand + City'), ('brand', 'Brand'), ('brand_city', 'Brand + City'), ('city', 'City'), ('seller', 'Seller'), ('search', 'Search')], db_index=True, max_length=30)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=160)),
                ('meta_keywords', models.TextField(blank=True, default='')),
                ('h1_heading', models.CharField(max_length=200)),
                ('intro_text', models.TextField(blank=True, default='')),
                ('buying_guide', models.TextField(blank=True, default='')),
                ('why_choose_us', models.TextField(blank=True, default='')),
                ('faq_json', models.JSONField(blank=True, default=list)),
                ('related_searches', models.JSONField(blank=True, default=list)),
                ('canonical_url', models.CharField(blank=True, default='', max_length=500)),
                ('og_title', models.CharField(blank=True, default='', max_length=200)),
                ('og_description', models.CharField(blank=True, default='', max_length=300)),
                ('og_image', models.URLField(blank=True, default='', max_length=500)),
                ('schema_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_pages', to='brands.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_pages', to='categories.category')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_pages', to='sellers.sellerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOFAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='seo.seopage')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='seopage',
            index=models.Index(fields=['page_type', 'is_active'], name='seo_seopage_page_ty_606dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='seopage',
            index=models.Index(fields=['category', 'city'], name='seo_seopage_categor_67abbc_idx'),
        ),
        migrations.AddIndex(
            model_name='seopage',
            index=models.Index(fields=['brand', 'city'], name='seo_seopage_brand_i_6ad9a4_idx'),
        ),
    ]
