# Generated by Django 6.0.6 on 2026-06-29 07:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0002_brand_country_brand_founded_year_brand_image_and_more'),
        ('categories', '0002_category_deleted_at_category_is_featured_and_more'),
        ('sellers', '0002_alter_sellerprofile_gstin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.URLField(max_length=500)),
                ('mobile_image', models.URLField(blank=True, max_length=500, null=True)),
                ('link_url', models.URLField(blank=True, max_length=500, null=True)),
                ('link_text', models.CharField(blank=True, max_length=100, null=True)),
                ('placement', models.CharField(choices=[('homepage', 'Homepage'), ('category', 'Category Page'), ('subcategory', 'Subcategory Page'), ('product', 'Product Page'), ('seller', 'Seller Page'), ('checkout', 'Checkout Page'), ('popup', 'Popup'), ('sidebar', 'Sidebar')], db_index=True, max_length=20)),
                ('sort_order', models.IntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='brands.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='categories.category')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='sellers.sellerprofile')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'banners',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['placement', 'is_active'], name='banners_placeme_c011a9_idx'), models.Index(fields=['is_active', 'start_date', 'end_date'], name='banners_is_acti_89fcaf_idx')],
            },
        ),
    ]
