# Generated by Django 6.0.6 on 2026-07-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_buyeraddress_latitude_buyeraddress_longitude'),
        ('orders', '0001_initial'),
        ('reviews', '0002_productreview_status_sellerreview_status'),
        ('sellers', '0002_alter_sellerprofile_gstin_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellerreview',
            unique_together={('buyer', 'order', 'seller')},
        ),
    ]
